name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set version var
        run: echo "VERSION=$(date "+%Y%m%d")-$(echo $GITHUB_SHA | cut -c1-7 | tr [:lower:] [:upper:])" >> $GITHUB_ENV
      - name: Build code
        run: |
          echo $VERSION > src/main/resources/views/_version.ftl
          ./gradlew installDist
      - name: docker login
        env:
          DOCKER_HUB_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
          DOCKER_HUB_ACCESS_TOKEN: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
        run: |
          docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_ACCESS_TOKEN
          - name: Build the Docker image
            run: docker build . --file Dockerfile --tag robinkanters/playlistmanager:$VERSION --tag robinkanters/playlistmanager:latest

          - name: Docker Push
            run: docker push -a robinkanters/playlistmanager
